// <auto-generated />
namespace ADN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newsmodel2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newsmodel2));
        
        string IMigrationMetadata.Id
        {
            get { return "201704050837474_newsmodel2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
